# Generated by Django 2.0.4 on 2018-04-30 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180430_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='label',
            new_name='title',
        ),
    ]
